# Generated by Django 5.0.7 on 2024-08-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationId', models.CharField(db_column='educationId', max_length=255, primary_key=True, serialize=False)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.CharField(blank=True, db_column='startDate', max_length=255, null=True)),
                ('endDate', models.CharField(blank=True, db_column='endDate', max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MercorUserProfile',
            fields=[
                ('userid', models.CharField(db_column='userId', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fullTimeSalary', models.CharField(blank=True, db_column='fullTimeSalary', max_length=255, null=True)),
                ('partTimeSalary', models.CharField(blank=True, db_column='partTimeSalary', max_length=255, null=True)),
                ('workExperience', models.JSONField(blank=True, db_column='workExperience', null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MercorUserProfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MercorUsers',
            fields=[
                ('userid', models.CharField(db_column='userId', max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.JSONField(blank=True, null=True)),
                ('profilePic', models.TextField(blank=True, db_column='profilePic', null=True)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('lastLogin', models.DateTimeField(db_column='lastLogin')),
                ('notes', models.TextField(blank=True, null=True)),
                ('referralCode', models.CharField(blank=True, db_column='referralCode', max_length=255, null=True, unique=True)),
                ('isGptEnabled', models.IntegerField(db_column='isGptEnabled')),
                ('preferredRole', models.CharField(blank=True, db_column='preferredRole', max_length=255, null=True)),
                ('fullTimeStatus', models.CharField(blank=True, db_column='fullTimeStatus', max_length=255, null=True)),
                ('workAvailability', models.CharField(blank=True, db_column='workAvailability', max_length=255, null=True)),
                ('fullTimeSalaryCurrency', models.CharField(blank=True, db_column='fullTimeSalaryCurrency', max_length=255, null=True)),
                ('fullTimeSalary', models.CharField(blank=True, db_column='fullTimeSalary', max_length=255, null=True)),
                ('partTimeSalaryCurrency', models.CharField(blank=True, db_column='partTimeSalaryCurrency', max_length=255, null=True)),
                ('partTimeSalary', models.CharField(blank=True, db_column='partTimeSalary', max_length=255, null=True)),
                ('fullTime', models.IntegerField(db_column='fullTime')),
                ('fullTimeAvailability', models.IntegerField(blank=True, db_column='fullTimeAvailability', null=True)),
                ('partTime', models.IntegerField(db_column='partTime')),
                ('partTimeAvailability', models.IntegerField(blank=True, db_column='partTimeAvailability', null=True)),
                ('w8BenUrl', models.JSONField(blank=True, db_column='w8BenUrl', null=True)),
                ('tosUrl', models.TextField(blank=True, db_column='tosUrl', null=True)),
                ('policyUrls', models.JSONField(blank=True, db_column='policyUrls', null=True)),
                ('isPreVetted', models.IntegerField(db_column='isPreVetted')),
                ('isActive', models.IntegerField(db_column='isActive')),
                ('isComplete', models.IntegerField(db_column='isComplete')),
                ('summary', models.TextField(blank=True, null=True)),
                ('preVettedAt', models.DateTimeField(blank=True, db_column='preVettedAt', null=True)),
            ],
            options={
                'db_table': 'MercorUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('personalInformationId', models.CharField(db_column='personalInformationId', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('email', models.JSONField(blank=True, null=True)),
                ('phone', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PersonalInformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillId', models.CharField(db_column='skillId', max_length=255, primary_key=True, serialize=False)),
                ('skillName', models.CharField(db_column='skillName', max_length=255)),
                ('skillValue', models.CharField(db_column='skillValue', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('resumeId', models.CharField(db_column='resumeId', max_length=255, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(db_column='createdAt')),
                ('updatedAt', models.DateTimeField(db_column='updatedAt')),
                ('source', models.CharField(max_length=255)),
                ('ocrText', models.TextField(blank=True, db_column='ocrText', null=True)),
                ('ocrEmail', models.CharField(blank=True, db_column='ocrEmail', max_length=255, null=True)),
                ('ocrGithubUsername', models.CharField(blank=True, db_column='ocrGithubUsername', max_length=255, null=True)),
                ('resumeBasedQuestions', models.TextField(blank=True, db_column='resumeBasedQuestions', null=True)),
                ('isInvitedToInterview', models.IntegerField(db_column='isInvitedToInterview')),
                ('reminderTasksIds', models.JSONField(blank=True, db_column='reminderTasksIds', null=True)),
            ],
            options={
                'db_table': 'UserResume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('workExperienceId', models.CharField(db_column='workExperienceId', max_length=255, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.CharField(blank=True, db_column='startDate', max_length=255, null=True)),
                ('endDate', models.CharField(blank=True, db_column='endDate', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('locationCity', models.CharField(blank=True, db_column='locationCity', max_length=255, null=True)),
                ('locationCountry', models.CharField(blank=True, db_column='locationCountry', max_length=255, null=True)),
            ],
            options={
                'db_table': 'WorkExperience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MercorUserSkills',
            fields=[
                ('userId', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ChatBotBrain.mercorusers')),
                ('isPrimary', models.IntegerField(db_column='isPrimary')),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'MercorUserSkills',
                'managed': False,
            },
        ),
    ]
